### ISSUE TITLE
Some ZEND_ACC_* constants have been removed in 5.0.0

### ISSUE THREAD

**Issue by cmb69** [krakjoe/uopz#67]
The constants `ZEND_ACC_CLASS`, `ZEND_ACC_INTERFACE` and `ZEND_ACC_TRAIT` seem to have been removed in uopz 5.0.0, even though they appear to be still useful for `uopz_flags($class, null, …)` (at least `0`  can be passed as `$flags` to "un-final-ize" a class in uopz 5.0.2). If these constants won't be re-introduced, I can fix the PHP manual accordingly.

Furthermore, obviously `ZEND_ACC_FETCH` has also been removed as of uopz 5.0.0. However, the constant is still mentioned in the README, what is rather confusing, particularly, as the `$flags` parameter of `uopz_flags()` apparently is now optional.

**Comment by cmb69** [comment]
Related to https://bugs.php.net/bug.php?id=76118.

**Comment by krakjoe** [comment]
ok, ZEND_ACC_CLASS was a dummy, not declared internally, but was for the purposes of an old API that was removed, so were INTERFACE and TRAIT.

Flags param is optional because it can be used to fetch flags and set them.

Feel free to update readme and or docs to reflect these changes ... unless you see value in adding them, in which case feel free to add them again.

I'll leave it to you, commit access in the mail ...

Sorry for leaving this so super long ...

**Comment by cmb69** [comment]
No problem regarding the delay! :)

I'll have a look at this as soon as possible.

**Comment by cmb69** [comment]
Doc updates: <http://svn.php.net/viewvc?view=revision&revision=346886> and <http://svn.php.net/viewvc?view=revision&revision=346885>.
